//! Minimal FFI bindings to `libibverbs`.
//!
//! Generated by `bindgen` from `<infiniband/verbs.h>`.
//! Only the subset of types, functions, and constants needed
//! by RDMAS are included.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Thin C wrappers for static inline functions that bindgen cannot see.
// These are compiled from src/wrapper_fns.c.
extern "C" {
    pub fn ibv_post_send_wr(
        qp: *mut ibv_qp,
        wr: *mut ibv_send_wr,
        bad_wr: *mut *mut ibv_send_wr,
    ) -> ::libc::c_int;

    pub fn ibv_post_recv_wr(
        qp: *mut ibv_qp,
        wr: *mut ibv_recv_wr,
        bad_wr: *mut *mut ibv_recv_wr,
    ) -> ::libc::c_int;

    pub fn ibv_poll_cq_wr(
        cq: *mut ibv_cq,
        num_entries: ::libc::c_int,
        wc: *mut ibv_wc,
    ) -> ::libc::c_int;

    pub fn ibv_req_notify_cq_wr(cq: *mut ibv_cq, solicited_only: ::libc::c_int) -> ::libc::c_int;

    pub fn ibv_query_port_attr(
        context: *mut ibv_context,
        port_num: u8,
        port_attr: *mut ibv_port_attr,
    ) -> ::libc::c_int;

    // Accessors for opaque ibv_mr fields
    pub fn ibv_mr_lkey(mr: *const ibv_mr) -> u32;
    pub fn ibv_mr_rkey(mr: *const ibv_mr) -> u32;
    pub fn ibv_mr_addr(mr: *const ibv_mr) -> *mut ::libc::c_void;
    pub fn ibv_mr_length(mr: *const ibv_mr) -> usize;

    // Accessor for opaque ibv_qp.qp_num field
    pub fn ibv_qp_get_qp_num(qp: *const ibv_qp) -> u32;
}
